---
title:  'Econometrics Lab'
author: "Daniel Carpenter"
date:   "Spring 2019"
fontsize: 12pt
geometry: margin=1in
output:
  github_document:
    toc: yes
    number_sections: yes
    toc_depth: 3
---
      
```{r defaultRendering, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, include = TRUE, message=FALSE, warning=FALSE)
```

```{r}
library(tidyverse)
library(wooldridge)
library(broom)
library(magrittr)
library(stargazer)
library(tsibble)
library(pdfetch)
library(tseries)
library(lubridate) # This package converts dates to a special date numbering system
library(devtools) # You will likely have to install this one
#library(fable) # This one takes forever to install:
#install.packages("devtools")
#devtools::install_github("tidyverts/fable")

# T-bill rates by quarter
df1 <- as_tibble(intqrt)
df1 %<>% mutate(quarter = seq(yq('1960:Q1'),yq('1990:Q4'), by = 'quarters')) # create quarter
df1 %<>% select(r3,quarter)
# Stock prices
df2 <- pdfetch_YAHOO(c("goog","aapl"), fields = c("adjclose"),
                     from = as.Date("2005-01-01"),
                     to = as.Date("2018-11-01"),
                     interval = "1d") %>%
  as.data.frame %>% rownames_to_column(var="date") %>%
  as_tibble %>% mutate(date=ymd(date)) # create date variable

df1 %<>% as_tsibble(index=quarter)
df2 %<>% as_tsibble(index=date) %>% # aggregate from daily to weekly
  1
index_by(year_week = yearweek(date)) %>%
  summarize(goog = mean(goog, na.rm=TRUE),
            aapl = mean(aapl, na.rm=TRUE))

#Plot t series on non-goog
autoplot(df1) + xlab("Year") + ylab("T-bill return")

#plot google
autoplot(df2) + xlab("Year") + ylab("Price")

#test for UNIT ROOT!!!!! high p value = unit root!, null = there is a unit root (reminder)
adf.test(df1$r3, k=1)
adf.test(df2$goog, k=1)
adf.test(df2$aapl, k=1)

#getting a lag variable
est.tbill <- lm(r3 ~ lag(r3,1), data=df1)
stargazer(est.tbill,type="text")
est.goog <- lm(goog ~ lag(goog,1), data=df2)
stargazer(est.goog,type="text")
est.aapl <- lm(aapl ~ lag(aapl,1), data=df2)
stargazer(est.aapl,type="text")

#output, autocorrelation uynder r3.(.909) if close to 1, then 



#FORECASTING
#1. pretend we dont have past years data (for testing purposes)

df2.short <- df2 %>% filter(year_week<yearweek("2018-10-01"))

#2. (Dont use this, use ARIMA Because unit root, we need to difference!!!!
#simple.goog <- lm(difference(goog) ~ lag(difference(goog)), data=df2)
#simple.aapl <- lm(difference(aapl) ~ lag(difference(aapl)), data=df2)


#CREATE FORECAST
auto.goog <- ARIMA(df2.short$goog)
auto.aapl <- ARIMA(df2.short$aapl)

#ARIMA gives naive and arima, which is conservative


#PLOT!
df2 %>%
  model(
    arima = ARIMA(goog),
    snaive = SNAIVE(goog)
  ) %>%
  forecast(h=12) %>% autoplot(filter(df2, year(year_week)>2017),level = NULL)
#forecast h = time frame
```